steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'user/Dockerfile', '-t', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA', 'user']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', '$_SERVICE_NAME', '--image', '$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA', '--region', '$_DEPLOY_REGION', '--platform', 'managed', '--allow-unauthenticated']

images: ['$_AR_HOSTNAME/$_AR_PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA']

substitutions:
  _SERVICE_NAME: nolasmspro-frontend
  _DEPLOY_REGION: asia-southeast1
  _AR_HOSTNAME: asia-southeast1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _AR_PROJECT_ID: nola-sms-pro

options:
  logging: CLOUD_LOGGING_ONLY
